extends: relaxed
rules:
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 200
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  truthy:
    check-keys: false
