---
# Ansible playbook for Ubuntu development machine setup
# Manages APT packages, Snap packages, PowerShell modules, pipx modules, VS Code extensions, and Git configuration

- name: Setup development environment on Ubuntu
  hosts: localhost
  connection: local
  gather_facts: yes
  # Define the become password at the play level so it's available to all tasks
  vars:
    ansible_become_pass: "{{ lookup('env', 'ANSIBLE_SUDO_PASS') }}"
    ansible_connection: local

  vars_files:
    - vars.yaml

  tasks:
    # System setup
    - name: Check if running in WSL
      ansible.builtin.shell: grep -q Microsoft /proc/version || (uname -r | grep -q microsoft)
      register: wsl_check
      ignore_errors: yes
      changed_when: false
      tags:
        - system
        - wsl

    - name: Set is_wsl fact
      ansible.builtin.set_fact:
        is_wsl: "{{ wsl_check.rc == 0 }}"
      tags:
        - system
        - wsl

    # APT setup
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes
      tags:
        - apt
        - update

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: yes
      become: yes
      tags:
        - apt
        - upgrade

    # Install prerequisite packages first
    - name: Install prerequisite APT packages
      ansible.builtin.apt:
        name: "{{ apt_packages_prereqs }}"
        state: present
      become: yes
      tags:
        - apt
        - prereqs
        - packages

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: yes
      tags:
        - apt
        - repositories

    # APT keys
    - name: Add APT keys
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: /tmp/key.asc
      loop: "{{ apt_keys }}"
      loop_control:
        label: "Adding key: {{ item.name }}"
      become: yes
      tags:
        - apt
        - keys

    - name: Install APT keys
      ansible.builtin.shell: |
        mkdir -p $(dirname {{ item.keyring }})
        cat /tmp/key.asc | gpg --dearmor -o {{ item.keyring }}
        chmod 644 {{ item.keyring }}
      loop: "{{ apt_keys }}"
      loop_control:
        label: "Installing key: {{ item.name }}"
      become: yes
      tags:
        - apt
        - keys

    # APT repositories
    - name: Add APT repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
      loop: "{{ apt_repositories }}"
      loop_control:
        label: "Adding repository: {{ item }}"
      become: yes
      tags:
        - apt
        - repositories

    # External repositories
    - name: Add external APT repositories
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        state: present
      loop: "{{ external_repositories }}"
      loop_control:
        label: "Adding external repository: {{ item.name }}"
      become: yes
      tags:
        - apt
        - repositories

    # APT packages
    - name: Install APT packages
      ansible.builtin.apt:
        name: "{{ apt_packages }}"
        state: present
      become: yes
      tags:
        - apt
        - packages

    # Snap packages
    - name: Install Snap packages (classic)
      community.general.snap:
        name: "{{ item.name }}"
        classic: yes
        state: present
      become: yes
      loop: "{{ snap_packages | selectattr('classic', 'defined') | selectattr('classic') | list }}"
      loop_control:
        label: "Installing classic snap: {{ item.name }}"
      tags:
        - snap
        - packages

    - name: Install Snap packages (regular)
      community.general.snap:
        name: "{{ item.name }}"
        state: present
      become: yes
      loop: "{{ snap_packages | rejectattr('classic', 'defined') | list }} + {{ snap_packages | selectattr('classic', 'defined') | rejectattr('classic') | list }}"
      loop_control:
        label: "Installing regular snap: {{ item.name }}"
      tags:
        - snap
        - packages

    # Docker setup
    - name: Install Docker
      block:
        - name: Install Docker GPG key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /tmp/docker.key
          become: yes

        - name: Install Docker GPG key to keyring
          ansible.builtin.shell: |
            cat /tmp/docker.key | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            chmod 644 /etc/apt/keyrings/docker.gpg
          become: yes

        - name: Add Docker repository
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
          become: yes

        - name: Install Docker packages
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present
          become: yes

        - name: Add user to docker group
          ansible.builtin.user:
            name: "{{ item }}"
            groups: docker
            append: yes
          loop: "{{ docker_users }}"
          become: yes
      when: install_docker | bool
      tags:
        - docker

    # PowerShell setup
    - name: Install PowerShell
      block:
        - name: Install PowerShell via apt
          ansible.builtin.apt:
            name: powershell
            state: present
          become: yes
      when: install_powershell | bool
      tags:
        - powershell
        - install

    # PowerShell modules
    - name: Install PowerShell modules
      ansible.builtin.command:
        cmd: pwsh -Command "Install-Module -Name {{ item }} -Force -Scope CurrentUser"
      loop: "{{ powershell_modules }}"
      register: pwsh_install_result
      changed_when: "'is already installed' not in pwsh_install_result.stdout"
      loop_control:
        label: "Installing PowerShell module: {{ item }}"
      when: install_powershell | bool
      tags:
        - powershell
        - modules

    # Node.js setup
    - name: Install Node.js using nvm
      block:
        - name: Download nvm install script
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh
            dest: /tmp/nvm-install.sh
            mode: '0755'

        - name: Install nvm
          ansible.builtin.shell: |
            bash /tmp/nvm-install.sh
          args:
            creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

        - name: Install Node.js using nvm
          ansible.builtin.shell: |
            export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install {{ node_version }}
            nvm alias default {{ node_version }}
          args:
            executable: /bin/bash
      when: install_nvm | bool
      tags:
        - nodejs
        - nvm

    # Python setup with pyenv
    - name: Install Python using pyenv
      block:
        - name: Download pyenv installer
          ansible.builtin.get_url:
            url: https://pyenv.run
            dest: /tmp/pyenv-installer.sh
            mode: '0755'

        - name: Install pyenv
          ansible.builtin.shell: |
            bash /tmp/pyenv-installer.sh
          args:
            creates: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"

        - name: Add pyenv to .bashrc if not already present
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            line: 'export PYENV_ROOT="$HOME/.pyenv"'
            state: present

        - name: Add pyenv PATH to .bashrc if not already present
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            line: 'export PATH="$PYENV_ROOT/bin:$PATH"'
            state: present

        - name: Add pyenv init to .bashrc if not already present
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            line: 'eval "$(pyenv init --path)"'
            state: present

        - name: Add pyenv init shell to .bashrc if not already present
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            line: 'eval "$(pyenv init -)"'
            state: present

        - name: Install Python versions
          ansible.builtin.shell: |
            export PYENV_ROOT="$HOME/.pyenv"
            export PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init --path)"
            eval "$(pyenv init -)"
            pyenv install {{ item }} -s
          loop: "{{ python_versions }}"
          args:
            executable: /bin/bash
          register: pyenv_install
          changed_when: pyenv_install.rc == 0
          failed_when: pyenv_install.rc != 0 and "already installed" not in pyenv_install.stderr

        - name: Set global Python version
          ansible.builtin.shell: |
            export PYENV_ROOT="$HOME/.pyenv"
            export PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init --path)"
            eval "$(pyenv init -)"
            pyenv global {{ default_python_version }}
          args:
            executable: /bin/bash
      when: install_pyenv | bool
      tags:
        - python
        - pyenv

    # pipx setup
    - name: Install pipx
      ansible.builtin.apt:
        name: pipx
        state: present
      become: yes
      tags:
        - pipx
        - install

    - name: Install pipx modules
      ansible.builtin.shell: |
        pipx install {{ item }}
      loop: "{{ pipx_modules }}"
      register: pipx_install_result
      changed_when: "'already installed' not in pipx_install_result.stdout"
      loop_control:
        label: "Installing pipx module: {{ item }}"
      tags:
        - pipx
        - modules

    # Ruby setup with rbenv
    - name: Install Ruby using rbenv
      block:
        - name: Clone rbenv
          ansible.builtin.git:
            repo: https://github.com/rbenv/rbenv.git
            dest: "{{ ansible_env.HOME }}/.rbenv"
            version: master

        - name: Clone ruby-build
          ansible.builtin.git:
            repo: https://github.com/rbenv/ruby-build.git
            dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
            version: master

        - name: Add rbenv to .bashrc if not already present
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
            state: present

        - name: Add rbenv init to .bashrc if not already present
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            line: 'eval "$(rbenv init -)"'
            state: present

        - name: Install Ruby version
          ansible.builtin.shell: |
            export PATH="$HOME/.rbenv/bin:$PATH"
            eval "$(rbenv init -)"
            rbenv install {{ ruby_version }} -s
          args:
            executable: /bin/bash
          register: rbenv_install
          changed_when: rbenv_install.rc == 0
          failed_when: rbenv_install.rc != 0 and "already installed" not in rbenv_install.stderr

        - name: Set global Ruby version
          ansible.builtin.shell: |
            export PATH="$HOME/.rbenv/bin:$PATH"
            eval "$(rbenv init -)"
            rbenv global {{ ruby_version }}
          args:
            executable: /bin/bash
      when: install_rbenv | bool
      tags:
        - ruby
        - rbenv

    # Go installation
    - name: Install Go
      block:
        - name: Download Go
          ansible.builtin.get_url:
            url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
            dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
          register: go_download

        - name: Remove existing Go installation if present
          ansible.builtin.file:
            path: /usr/local/go
            state: absent
          become: yes
          when: go_download.changed

        - name: Extract Go
          ansible.builtin.unarchive:
            src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
            dest: /usr/local
            remote_src: yes
          become: yes
          when: go_download.changed

        - name: Add Go to PATH in .bashrc if not already present
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            line: 'export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin'
            state: present
      when: install_go | bool
      tags:
        - go

    # Rust installation
    - name: Install Rust
      block:
        - name: Download rustup installer
          ansible.builtin.get_url:
            url: https://sh.rustup.rs
            dest: /tmp/rustup.sh
            mode: '0755'

        - name: Install Rust
          ansible.builtin.shell: |
            /tmp/rustup.sh -y
          args:
            creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
      when: install_rust | bool
      tags:
        - rust

    # .NET installation
    - name: Install .NET SDK
      block:
        - name: Install .NET SDK
          ansible.builtin.apt:
            name: "dotnet-sdk-{{ dotnet_version }}"
            state: present
          become: yes
      when: install_dotnet | bool
      tags:
        - dotnet

    # VS Code extension setup
    - name: Ensure VS Code extensions are installed
      ansible.builtin.command:
        cmd: code --install-extension {{ item }}
      loop: "{{ vscode_extensions }}"
      register: vscode_ext_result
      changed_when: "'already installed' not in vscode_ext_result.stdout"
      loop_control:
        label: "Installing VS Code extension: {{ item }}"
      tags:
        - vscode
        - extensions

    # Git LFS setup
    - name: Ensure Git LFS is initialized
      ansible.builtin.command:
        cmd: git lfs install --system
      register: git_lfs_result
      changed_when: "'Already initialized' not in git_lfs_result.stdout"
      tags:
        - git
        - lfs

    # Git configuration
    - name: Configure Git user.name
      ansible.builtin.command:
        cmd: git config --global user.name "{{ git_user_name }}"
      register: git_name_result
      changed_when: git_name_result.rc == 0
      when: git_user_name is defined and git_user_name != ""
      tags:
        - git
        - config

    - name: Configure Git user.email
      ansible.builtin.command:
        cmd: git config --global user.email "{{ git_user_email }}"
      register: git_email_result
      changed_when: git_email_result.rc == 0
      when: git_user_email is defined and git_user_email != ""
      tags:
        - git
        - config

    # Git Credential Manager
    - name: Install Git Credential Manager
      block:
        - name: Download and install Git Credential Manager
          ansible.builtin.apt:
            deb: https://github.com/git-ecosystem/git-credential-manager/releases/latest/download/gcm-linux_amd64.deb
          become: yes

        - name: Configure Git to use Git Credential Manager
          ansible.builtin.command:
            cmd: git config --global credential.helper /usr/bin/git-credential-manager
          register: git_gcm_result
          changed_when: git_gcm_result.rc == 0
      when: install_git_credential_manager | bool
      tags:
        - git
        - git-credential-manager

    # bash-git-prompt
    - name: Install bash-git-prompt
      block:
        - name: Clone bash-git-prompt repository
          ansible.builtin.git:
            repo: https://github.com/magicmonty/bash-git-prompt.git
            dest: "{{ ansible_env.HOME }}/.bash-git-prompt"
            version: master

        - name: Add bash-git-prompt to .bashrc if not already present
          ansible.builtin.blockinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            marker: "# {mark} BASH GIT PROMPT CONFIGURATION"
            block: |
              if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
                  GIT_PROMPT_ONLY_IN_REPO=1
                  source $HOME/.bash-git-prompt/gitprompt.sh
              fi
            state: present
      when: install_bash_git_prompt | bool
      tags:
        - git
        - bash-git-prompt

    # Custom user commands
    - name: Execute custom user commands
      ansible.builtin.shell: "{{ item.command }}"
      loop: "{{ custom_commands_user }}"
      loop_control:
        label: "Executing: {{ item.description }}"
      tags:
        - custom
        - user-commands

    # Custom elevated commands
    - name: Execute custom elevated commands
      ansible.builtin.shell: "{{ item.command }}"
      become: yes
      loop: "{{ custom_commands_elevated }}"
      loop_control:
        label: "Executing: {{ item.description }}"
      tags:
        - custom
        - elevated-commands

    # Execute custom script if defined
    - name: Check if custom script exists
      ansible.builtin.stat:
        path: "{{ custom_script }}"
      register: custom_script_stat
      when: custom_script is defined and custom_script != ""
      tags:
        - custom
        - script

    - name: Make custom script executable
      ansible.builtin.file:
        path: "{{ custom_script }}"
        mode: '0755'
      when: custom_script is defined and custom_script != "" and custom_script_stat.stat.exists
      tags:
        - custom
        - script

    - name: Execute custom script
      ansible.builtin.command:
        cmd: "{{ custom_script }}"
      when: custom_script is defined and custom_script != "" and custom_script_stat.stat.exists
      tags:
        - custom
        - script

    # Notify user of completion
    - name: Setup complete
      ansible.builtin.debug:
        msg: "Ubuntu development environment setup complete!"
      tags:
        - always
