---
# Ansible playbook for macOS development machine setup
# Manages Homebrew packages, PowerShell modules, pipx modules, VS Code extensions, and Git configuration

- name: Setup development environment on macOS
  hosts: localhost
  connection: local
  gather_facts: yes
  # Define the become password at the play level so it's available to all tasks
  vars:
    ansible_become_pass: "{{ lookup('env', 'ANSIBLE_SUDO_PASS') }}"
    ansible_connection: local

  vars_files:
    - vars.yaml

  tasks:
    # Rosetta 2 installation (optional)
    - name: Check if system is Apple Silicon
      ansible.builtin.command:
        cmd: uname -m
      register: arch_check
      changed_when: false
      when: install_rosetta | bool
      tags:
        - system
        - rosetta

    - name: Check if Rosetta 2 is already installed
      ansible.builtin.command:
        cmd: pgrep -q oahd
      register: rosetta_check
      ignore_errors: yes
      changed_when: false
      when:
        - install_rosetta | bool
        - arch_check.stdout == "arm64"
      tags:
        - system
        - rosetta

    - name: Install Rosetta 2 (with become_method=sudo)
      ansible.builtin.command:
        cmd: softwareupdate --install-rosetta --agree-to-license
      become: yes
      become_method: sudo
      when:
        - install_rosetta | bool
        - arch_check.stdout == "arm64"
        - rosetta_check.rc != 0
      register: rosetta_install
      changed_when: rosetta_install.rc == 0
      tags:
        - system
        - rosetta

    # Homebrew setup
    - name: Ensure Homebrew taps are added
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      ignore_errors: yes
      loop: "{{ homebrew_taps }}"
      loop_control:
        label: "Adding tap: {{ item }}"
      tags:
        - homebrew
        - taps

    - name: Check if Homebrew casks are already installed
      ansible.builtin.command:
        cmd: "brew list --cask {{ item }}"
      ignore_errors: yes
      loop: "{{ homebrew_casks }}"
      register: brew_cask_check
      changed_when: false
      failed_when: false
      loop_control:
        label: "Checking cask: {{ item }}"
      tags:
        - homebrew
        - casks

    - name: Install missing Homebrew casks
      ansible.builtin.shell:
        cmd: "brew install --cask {{ item.0 }}"
      environment:
        SUDO_ASKPASS: "{{ lookup('env', 'SUDO_ASKPASS') }}"
        HOMEBREW_SUDO_ASKPASS: "{{ lookup('env', 'SUDO_ASKPASS') }}"
      loop: "{{ homebrew_casks | zip(brew_cask_check.results) | list }}"
      when: item.1.rc != 0
      register: brew_cask_install_result
      changed_when: brew_cask_install_result.rc == 0
      failed_when: false
      loop_control:
        label: "Installing cask: {{ item.0 }}"
      tags:
        - homebrew
        - casks

    - name: Ensure Homebrew formulae are installed
      community.general.homebrew:
        name: "{{ item }}"
        state: present
        update_homebrew: yes
      ignore_errors: yes
      loop: "{{ homebrew_formulae }}"
      loop_control:
        label: "Installing formula: {{ item }}"
      tags:
        - homebrew
        - formulae

    # Refresh Ansible inventory
    # This ensures that the inventory is up-to-date after Homebrew installations which add to the PATH
    - meta: refresh_inventory

    # PowerShell module setup
    - name: Ensure PowerShell modules are installed
      ansible.builtin.command:
        cmd: pwsh -Command "Install-PSResource -Name {{ item }} -TrustRepository"
      ignore_errors: yes
      loop: "{{ powershell_modules }}"
      register: pwsh_install_result
      changed_when: "'is already installed' not in pwsh_install_result.stdout"
      loop_control:
        label: "Installing PowerShell module: {{ item }}"
      tags:
        - powershell
        - modules

    # pipx module setup
    - name: Ensure pipx modules are installed
      ansible.builtin.command:
        cmd: pipx install {{ item }}
      ignore_errors: yes
      loop: "{{ pipx_packages }}"
      register: pipx_install_result
      changed_when: "'already installed' not in pipx_install_result.stdout"
      loop_control:
        label: "Installing pipx module: {{ item }}"
      tags:
        - pipx
        - modules

    # npm global package setup
    - name: Check if npm packages are already installed
      ansible.builtin.command:
        cmd: npm list -g {{ item }}
      register: npm_check_result
      changed_when: false
      failed_when: false
      loop: "{{ npm_global_packages | default([]) }}"
      loop_control:
        label: "Checking npm package: {{ item }}"
      tags:
        - npm
        - packages

    - name: Ensure npm global packages are installed
      ansible.builtin.command:
        cmd: npm install -g {{ item.0 }}
      ignore_errors: yes
      loop: "{{ npm_global_packages | default([]) | zip(npm_check_result.results) | list }}"
      when: "item.1.rc != 0"
      register: npm_install_result
      changed_when: "npm_install_result.rc == 0"
      loop_control:
        label: "Installing npm package: {{ item.0 }}"
      tags:
        - npm
        - packages

    # .NET Global Tools setup
    - name: Check if dotnet is installed
      ansible.builtin.command:
        cmd: dotnet --version
      register: dotnet_check
      changed_when: false
      failed_when: false
      tags:
        - dotnet
        - tools

    - name: Check if .NET tools are already installed
      ansible.builtin.command:
        cmd: dotnet tool list -g
      register: dotnet_tools_list
      changed_when: false
      failed_when: false
      when: dotnet_check.rc == 0
      tags:
        - dotnet
        - tools

    - name: Ensure .NET global tools are installed
      ansible.builtin.command:
        cmd: dotnet tool install -g {{ item }}
      ignore_errors: yes
      loop: "{{ dotnet_tools | default([]) }}"
      register: dotnet_tool_install_result
      changed_when: "'already installed' not in dotnet_tool_install_result.stderr and dotnet_tool_install_result.rc == 0"
      failed_when: false
      when:
        - dotnet_check.rc == 0
        - item not in dotnet_tools_list.stdout
      loop_control:
        label: "Installing .NET tool: {{ item }}"
      tags:
        - dotnet
        - tools

    # VS Code extension setup
    - name: Ensure VS Code extensions are installed
      ansible.builtin.command:
        cmd: code --install-extension {{ item }}
      ignore_errors: yes
      loop: "{{ vscode_extensions }}"
      register: vscode_ext_result
      changed_when: "'already installed' not in vscode_ext_result.stdout"
      loop_control:
        label: "Installing VS Code extension: {{ item }}"
      tags:
        - vscode
        - extensions

    # Git LFS setup
    - name: Ensure Git LFS is initialized
      ansible.builtin.command:
        cmd: git lfs install --system
      register: git_lfs_result
      changed_when: "'Already initialized' not in git_lfs_result.stdout"
      tags:
        - git
        - lfs

    # Git configuration
    - name: Configure Git user.name
      ansible.builtin.command:
        cmd: git config --global user.name "{{ git_user_name }}"
      register: git_name_result
      changed_when: git_name_result.rc == 0
      when: git_user_name is defined and git_user_name != ""
      tags:
        - git
        - config

    - name: Configure Git user.email
      ansible.builtin.command:
        cmd: git config --global user.email "{{ git_user_email }}"
      register: git_email_result
      changed_when: git_email_result.rc == 0
      when: git_user_email is defined and git_user_email != ""
      tags:
        - git
        - config

    # Custom macOS commands and preferences - Non-elevated (user) commands
    - name: Execute custom macOS commands (non-elevated)
      ansible.builtin.shell:
        cmd: "{{ item }}"
        executable: /bin/bash
      loop: "{{ custom_commands_user | default([]) }}"
      register: custom_command_user_result
      changed_when: custom_command_user_result.rc == 0
      ignore_errors: yes
      loop_control:
        label: "Executing user command: '{{ item | truncate(40) }}'"
      tags:
        - macos
        - preferences
        - user-commands

    # Custom macOS commands that require elevated privileges
    - name: Execute custom macOS commands (elevated)
      ansible.builtin.shell:
        cmd: "{{ item }}"
        executable: /bin/bash
      loop: "{{ custom_commands_elevated | default([]) }}"
      register: custom_command_elevated_result
      changed_when: custom_command_elevated_result.rc == 0
      ignore_errors: yes
      become: yes
      become_method: sudo
      loop_control:
        label: "Executing elevated command: '{{ item | truncate(40) }}'"
      tags:
        - macos
        - preferences
        - elevated-commands

    # Display results for debugging custom commands (only when verbose)
    - name: Show custom command results (non-elevated)
      ansible.builtin.debug:
        var: custom_command_user_result
      when:
        - custom_command_user_result is defined
        - ansible_verbosity > 0
      tags:
        - macos
        - preferences
        - user-commands

    - name: Show custom command results (elevated)
      ansible.builtin.debug:
        var: custom_command_elevated_result
      when:
        - custom_command_elevated_result is defined
        - ansible_verbosity > 0
      tags:
        - macos
        - preferences
        - elevated-commands

    # Execute custom script if defined
    - name: Check if custom script exists
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/{{ custom_script | default('') }}"
      register: script_stat
      when: custom_script is defined and custom_script != ""
      tags:
        - custom
        - script

    - name: Make custom script executable
      ansible.builtin.file:
        path: "{{ playbook_dir }}/{{ custom_script }}"
        mode: '0755'
      when:
        - custom_script is defined and custom_script != ""
        - script_stat.stat.exists | bool
      tags:
        - custom
        - script

    - name: Execute custom script
      ansible.builtin.command:
        cmd: "{{ playbook_dir }}/{{ custom_script }}"
      register: custom_script_result
      changed_when: custom_script_result.rc == 0
      when:
        - custom_script is defined and custom_script != ""
        - script_stat.stat.exists | bool
      tags:
        - custom
        - script

    # Notify user of completion
    - name: Setup complete
      ansible.builtin.debug:
        msg: "Development environment setup completed successfully!"
      tags:
        - always
