# vars.yaml
# Externalized variables for Ansible setup

# System configuration
# Enable WSL-specific configurations if running in WSL
is_wsl: false  # Set to true if running in WSL

# DNF prerequisite packages (installed first)
# These are essential packages needed for basic system operations and some specific applications
dnf_packages_prereqs:
  # Basic networking and certificate tools
  - name: ca-certificates
  - name: curl
  - name: wget
  # For adding external repositories
  - name: dnf-plugins-core

# External DNF repositories
# This uses the ansible.builtin.yum_repository module
external_dnf_repositories:
  # Azure CLI repository
  - name: azure-cli
    description: Azure CLI
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true
  # Docker CE repository
  - name: docker-ce
    description: Docker CE Stable
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/stable"
    gpgkey: https://download.docker.com/linux/fedora/gpg
    gpgcheck: true
  # GitHub CLI repository
  - name: github-cli
    description: GitHub CLI
    baseurl: https://cli.github.com/packages/rpm
    gpgkey: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x23F3D4EA75716059
    gpgcheck: true
  # Google Chrome repository
  - name: google-chrome
    description: Google Chrome
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    gpgcheck: true
    supported_architectures:
      - x86_64
  # HashiCorp repository
  - name: hashicorp
    description: HashiCorp Stable
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    gpgcheck: true
  # Microsoft packages repository
  - name: packages-microsoft-com-prod
    description: Microsoft packages
    baseurl: https://packages.microsoft.com/yumrepos/microsoft-fedora43-prod
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true
  # NodeSource repository for Node.js LTS
  - name: nodesource
    description: NodeSource Node.js 22.x
    baseurl: https://rpm.nodesource.com/pub_22.x/nodistro/nodejs/$basearch
    gpgkey: https://rpm.nodesource.com/gpgkey/nodesource-repo.gpg.key
    gpgcheck: true
  # Visual Studio Code repository
  - name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true
  # RPM Fusion Free repository
  - name: rpmfusion-free
    description: RPM Fusion Free
    baseurl: "https://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/"
    gpgkey: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-$releasever"
    gpgcheck: true
  # RPM Fusion Nonfree repository
  - name: rpmfusion-nonfree
    description: RPM Fusion Nonfree
    baseurl: "https://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/$basearch/os/"
    gpgkey: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever"
    gpgcheck: true

# DNF packages
dnf_packages:
  # Development tools (replaces build-essential)
  - name: gcc
  - name: gcc-c++
  - name: glibc-devel
  - name: cmake
  - name: make
  - name: pkg-config
  - name: autoconf
  - name: automake
  - name: libtool
  - name: unzip
  # Python dependencies
  - name: openssl-devel
  - name: zlib-devel
  - name: bzip2-devel
  - name: readline-devel
  - name: sqlite-devel
  - name: llvm
  - name: ncurses-devel
  - name: tk-devel
  - name: libffi-devel
  - name: xz-devel
  - name: python3-pip
  # Git and version control
  - name: git
  - name: git-lfs
  # Shell tools
  - name: zsh
  - name: fish
  - name: bash-completion
  # Other tools
  - name: jq
  - name: maven
  - name: direnv
  - name: azure-cli
  - name: docker-ce
  - name: docker-ce-cli
  - name: containerd.io
  - name: docker-buildx-plugin
  - name: docker-compose-plugin
  - name: dotnet-sdk-9.0
  - name: ffmpeg-free
  - name: fzf
  - name: gh
  - name: golang
  - name: google-chrome-stable
    supported_architectures:
      - x86_64
  - name: microsoft-edge-stable
    supported_architectures:
      - x86_64
  # Node.js from NodeSource repository
  - name: nodejs
  - name: packer
  - name: pipx
  - name: ruby
  - name: ruby-devel
  - name: rust
  - name: cargo
  # QEMU virtualization packages
  - name: qemu-system-x86
  - name: qemu-user-static
  - name: qemu-img
  - name: qemu-kvm
  - name: libvirt
  - name: virt-manager
  - name: bridge-utils
  # amd64 only, arm64 not supported
  - name: steam
    supported_architectures:
      - x86_64
  - name: terraform
  - name: vault
  # Visual Studio Code
  - name: code
  # wget
  - name: wget
  # Zulu OpenJDK
  - name: zsh-autosuggestions
  - name: zsh-syntax-highlighting

# Flatpak packages
flatpak_packages:
  # x86_64 only
  - name: com.jgraph.drawio.desktop
    supported_architectures:
      - x86_64
  - name: com.slack.Slack
    supported_architectures:
      - x86_64

# PowerShell modules
powershell_modules:
  - AWS.Tools.Common
  - Az.Accounts
  - Microsoft.Graph.Authentication
  - MSAL.PS
  - Pester
  - platyPS
  - posh-git
  - powershell-yaml
  - PowerShellBuild
  - psake
  - PSGraphQL
  - PSJsonWebToken
  - PSReadLine
  - PSScriptAnalyzer
  - PSTcpIp
  - Terminal-Icons

# pipx modules
pipx_packages:
  - aws-sam-cli
  - cfn-lint
  - poetry
  - ruff
  - taskcat
  - uv

# npm global packages
npm_global_packages:
  - '@github/copilot'
  - '@vue/cli'
  - aws-cdk
  - azure-functions-core-tools@4
  - npmrc
  - serverless

# .NET Global Tools
dotnet_tools:
  - Amazon.Lambda.Tools
  # This is the preferred way to install Git Credential Manager on Linux
  # for all architectures since it can be updated via the dotnet cli.
  - git-credential-manager
  # This is the preferred way to install PowerShell on Linux
  # since it can be updated via the dotnet cli.
  # Add dotnet tools to your PATH,
  # this will allow you to run `pwsh` from the terminal.
  - powershell

# VS Code extensions (same as macOS for consistency)
# You can list your VS Code extensions with the command:
# code --list-extensions
vscode_extensions:
  # Packer
  - 4ops.packer
  # Project Manager
  - alefragnani.project-manager
  # Swagger Viewer
  - arjun.swagger-viewer
  # CloudFormation Linter
  - aws-scripting-guy.cform
  # Ruff
  - charliermarsh.ruff
  # gitignore
  - codezombiech.gitignore
  # Markdownlint
  - davidanson.vscode-markdownlint
  # ESLint
  - dbaeumer.vscode-eslint
  # Docker
  - docker.docker
  # Git Extension Pack
  - donjayamanne.git-extension-pack
  # Git History
  - donjayamanne.githistory
  # GitLens — Git supercharged
  - eamodio.gitlens
  # Prettier - Code formatter
  - esbenp.prettier-vscode
  # Solution Explorer
  - fernandoescolar.vscode-solution-explorer
  # GitHub Copilot
  - github.copilot
  # GitHub Copilot Chat
  - github.copilot-chat
  # GitHub Actions
  - github.vscode-github-actions
  # GitHub Pull Requests and Issues
  - github.vscode-pull-request-github
  # Go
  - golang.go
  # Excel Viewer
  - grapecity.gc-excelviewer
  # Test Explorer UI
  - hbenl.vscode-test-explorer
  # Kusto Syntax Highlighting
  - josin.kusto-syntax-highlighting
  # DocComment
  - k--kato.docomment
  # Render CRLF
  - medo64.render-crlf
  # Git Graph
  - mhutchie.git-graph
  # Swagger Doc Viewer
  - mimarec.swagger-doc-viewer
  # Prettify JSON
  - mohsen1.prettify-json
  # Azure Functions
  - ms-azuretools.vscode-azurefunctions
  # Azure Resource Groups
  - ms-azuretools.vscode-azureresourcegroups
  # Bicep
  - ms-azuretools.vscode-bicep
  # Azure Containers
  - ms-azuretools.vscode-containers
  # Docker (Microsoft)
  - ms-azuretools.vscode-docker
  # .NET Dev Kit
  - ms-dotnettools.csdevkit
  # C#
  - ms-dotnettools.csharp
  # .NET Install Tool for Extension Authors
  - ms-dotnettools.vscode-dotnet-runtime
  # Kubernetes
  - ms-kubernetes-tools.vscode-kubernetes-tools
  # Data Workspace
  - ms-mssql.data-workspace-vscode
  # SQL Server (mssql)
  - ms-mssql.mssql
  # SQL Bindings
  - ms-mssql.sql-bindings-vscode
  # SQL Database Projects
  - ms-mssql.sql-database-projects-vscode
  # Debugpy
  - ms-python.debugpy
  # isort
  - ms-python.isort
  # Python
  - ms-python.python
  # Pylance
  - ms-python.vscode-pylance
  # Jupyter
  - ms-toolsai.jupyter
  # Jupyter Keymap
  - ms-toolsai.jupyter-keymap
  # Jupyter Renderers
  - ms-toolsai.jupyter-renderers
  # Jupyter Cell Tags
  - ms-toolsai.vscode-jupyter-cell-tags
  # Jupyter Slideshow
  - ms-toolsai.vscode-jupyter-slideshow
  # Remote - Containers
  - ms-vscode-remote.remote-containers
  # Remote - SSH
  - ms-vscode-remote.remote-ssh
  # Remote - SSH: Editing Configuration Files
  - ms-vscode-remote.remote-ssh-edit
  # Remote - WSL
  - ms-vscode-remote.remote-wsl
  # Remote Development Extension Pack
  - ms-vscode-remote.vscode-remote-extensionpack
  # CMake Tools
  - ms-vscode.cmake-tools
  # C/C++ Extension Pack
  - ms-vscode.cpptools
  # C/C++ Extension Pack
  - ms-vscode.cpptools-extension-pack
  # C/C++ Themes
  - ms-vscode.cpptools-themes
  # Hex Editor
  - ms-vscode.hexeditor
  # Makefile Tools
  - ms-vscode.makefile-tools
  # PowerShell
  - ms-vscode.powershell
  # Remote Explorer
  - ms-vscode.remote-explorer
  # Remote Server
  - ms-vscode.remote-server
  # Test Adapter Converter
  - ms-vscode.test-adapter-converter
  # Live Share
  - ms-vsliveshare.vsliveshare
  # Azure Resource Manager (ARM) Tools
  - msazurermtools.azurerm-vscode-tools
  # Vetur
  - octref.vetur
  # Indent Rainbow
  - oderwat.indent-rainbow
  # Parallels Desktop
  - parallelsdesktop.parallels-desktop
  # Pester Test Adapter
  - pspester.pester-test
  # Thunder Client
  - rangav.vscode-thunder-client
  # Language Support for Java(TM) by Red Hat
  - redhat.java
  # VSCode Commons
  - redhat.vscode-commons
  # YAML
  - redhat.vscode-yaml
  # C# Test Adapter
  - samirat.csharp-test-adapter
  # SCSS Formatter
  - sibiraj-s.vscode-scss-formatter
  # Code Spell Checker
  - streetsidesoftware.code-spell-checker
  # Markdown Table Formatter
  - takumii.markdowntable
  # Microsoft Teams Toolkit
  - teamsdevapp.ms-teams-vscode-extension
  # Adaptive Cards
  - teamsdevapp.vscode-adaptive-cards
  # CMake
  - twxs.cmake
  # Inline Values PowerShell
  - tylerleonhardt.vscode-inline-values-powershell
  # Sort Lines
  - tyriar.sort-lines
  # Error Lens
  - usernamehw.errorlens
  # IntelliCode API Usage Examples
  - visualstudioexptteam.intellicode-api-usage-examples
  # IntelliCode
  - visualstudioexptteam.vscodeintellicode
  # Gradle for Java
  - vscjava.vscode-gradle
  # Java Debugger
  - vscjava.vscode-java-debug
  # Java Dependency Viewer
  - vscjava.vscode-java-dependency
  # Java Extension Pack
  - vscjava.vscode-java-pack
  # Java Test Runner
  - vscjava.vscode-java-test
  # Maven for Java
  - vscjava.vscode-maven
  # VSCode Icons
  - vscode-icons-team.vscode-icons
  # CodeTour
  - vsls-contrib.codetour
  # Volar
  - vue.volar
  # Git Blame
  - waderyan.gitblame
  # Markdown All in One
  - yzhang.markdown-all-in-one
  # Open in GitHub
  - ziyasal.vscode-open-in-github

# Git configuration
git_user_email: ''  # REQUIRED: Set your email here or pass via command line with -e flag
git_user_name: "{{ ansible_user_id }}"  # Defaults to the current user's username

# Custom commands and scripts (optional)
# These commands will be executed as the current user (non-elevated)
custom_commands_user:
  # Add commands to execute as the current user
  - command: pipx ensurepath
    description: Ensure pipx is in PATH
  # Update PowerShell help
  - command: ~/.dotnet/tools/pwsh -Command "Update-Help -Force -ErrorAction SilentlyContinue"
    description: Update PowerShell help documentation
  # Set PSResource Repository PSGallery as trusted repository
  - command: ~/.dotnet/tools/pwsh -Command "Set-PSRepository -Name PSGallery -Trusted"
    description: Set PSResource Repository PSGallery as trusted repository
  # Install Git LFS
  - command: git lfs install
    description: Install Git LFS
  # Set git configs
  - command: git config --global commit.gpgsign true
    description: Enable GPG signing for commits
  - command: git config --global init.defaultBranch main
    description: Set default branch to main
  - command: git config --global gpg.program /usr/bin/gpg
    description: Set GPG program path for Fedora
  - command: git config --global push.default current
    description: Set push default to current branch
  - command: git config --global push.autoSetupRemote true
    description: Enable automatic remote setup for push
  - command: git config --global user.signingKey 787AEF0BAE232359
    description: Set GPG signing key
  # Azure CLI configuration
  - command: az bicep install
    description: Install Bicep CLI via Azure CLI
  - command: az config set auto-upgrade.enable=yes
    description: Enable automatic upgrades for Azure CLI

# These commands will be executed with elevated privileges (sudo)
custom_commands_elevated:
  # Add commands to execute with elevated privileges
  # Add Docker User
  - command: usermod -aG docker $USER
    description: Add current user to Docker group

# Custom script path (optional)
# Provide the path to a custom script that will be executed at the end of the setup
custom_script: ./examples/custom_script.sh
